### ISSUE TITLE
이미지 API 문제

### ISSUE THREAD

**Issue by yunseo-h68** [Ho-Joon-Kim/dsm-infographic#13]
frontend 테스트 중 아래와 같은 에러가 발생했습니다.
```
GET /api/info/desc?imgid=1 500 171.746 ms - 1419
GET /api/info/desc?imgid=2 500 14.357 ms - 1419
GET /api/info/desc?imgid=3 500 24.171 ms - 1419
_http_outgoing.js:618
    throw new ERR_INVALID_ARG_TYPE('first argument',
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string or Buffer. Received type undefined
    at write_ (_http_outgoing.js:618:11)
    at ServerResponse.write (_http_outgoing.js:586:15)
    at ReadFileContext.callback (/home/yunseo/yunseo-h68/dsm-infographic/dsm-infographic/backend/routes/info/img.js:14:17)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:250:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! backend@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the backend@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yunseo/.npm/_logs/2019-10-24T10_43_18_337Z-debug.log
```

백엔드 서버를 켜고 http://localhost:3000/api/info/desc?imgid=1로 접속했을 때 아래와 같은 화면이 나옵니다. no such file or directory, open '../../public/info/1.txt'

확인해보시고 수정해주세요.

**Comment by yunseo-h68** [comment]
```
Error: ENOENT: no such file or directory, open '../../public/info/1로.txt'
    at Object.openSync (fs.js:451:3)
    at Object.readFileSync (fs.js:353:35)
    at /home/yunseo/yunseo-h68/dsm-infographic/dsm-infographic/backend/routes/info/desc.js:10:19
    at Layer.handle [as handle_request] (/home/yunseo/yunseo-h68/dsm-infographic/dsm-infographic/backend/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/yunseo/yunseo-h68/dsm-infographic/dsm-infographic/backend/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/yunseo/yunseo-h68/dsm-infographic/dsm-infographic/backend/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/yunseo/yunseo-h68/dsm-infographic/dsm-infographic/backend/node_modules/express/lib/router/layer.js:95:5)
    at /home/yunseo/yunseo-h68/dsm-infographic/dsm-infographic/backend/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/yunseo/yunseo-h68/dsm-infographic/dsm-infographic/backend/node_modules/express/lib/router/index.js:335:12)
    at next (/home/yunseo/yunseo-h68/dsm-infographic/dsm-infographic/backend/node_modules/express/lib/router/index.js:275:10)
```

**Comment by Ho-Joon-Kim** [comment]
아마 그거 3000이 아니라 8080으로 접속해야 되는것 같음

**Comment by yunseo-h68** [comment]
info.js에서 상대주소 에러인거 같습니다.

```
//info.js
var filename = `../public/info/${info_id}.png`;
```

**Comment by Ho-Joon-Kim** [comment]
.....제가 커밋한거 풀하시고 말하시는거죠?

**Comment by Ho-Joon-Kim** [comment]
info.js 에서 img.js로 이름 바꿔서 푸시한것 같은데...

**Comment by yunseo-h68** [comment]
에러 해결 방법 찾았습니다.

먼저 파일 경로 변수를 아래와 같이 수정하고,
```js
//img.js
var filename = `public/info/${ info_id}.PNG`;
```

원래 200이라는 int형을 String형으로 바꿔서 보내줍니다.
```js
//img.js
res.writeHead(res.statusCode.toString(), { "Context-Type": "image/png" });
```

이렇게 수정해주세요.

**Comment by yunseo-h68** [comment]
이미지 API 문제 해결
